version: "3"
services:
  api:
    build: .
    container_name: valheim-dashboard-api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: "production"
    command: /bin/sh -c "cd packages/api; node dist/main.js"
  ui:
    build: .
    container_name: valheim-dashboard-ui
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: "production"
    command: /bin/sh -c "cd packages/ui; serve -s build"
